name = "cron_worker"
type = "javascript"
zone_id = ""
account_id = "b0eb1f5510cb71344976cb9cac51e2af"
route = ""
workers_dev = true
compatibility_date = "2022-01-17"

kv_namespaces = [
    { binding = "cron_worker", id = "5af2d9d68cec4486a3f8bb28af2adfb5" }
]

[miniflare]
env_path = ".env"

[build]
command = "npm install && npm run build"
[build.upload]
format = "service-worker"
